version: '3'

services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/ecommerce
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis
    env_file:
      - .env

  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ecommerce
    ports:
      - "5432:5432"

  redis:
    image: redis
    ports:
      - "6379:6379"
    env_file:
      - .env

  elasticsearch:
    image: 'docker.elastic.co/elasticsearch/elasticsearch:8.7.0'
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "9200:9200"
    volumes:
      - esdata:/usr/share/elasticsearch/data

volumes:
  esdata:

    # Create container. network, ... from "docker compose " file:
    # -d deamon/ background mode
    # docker compose up -d
    # if you want to start only specified container/ server
    # -> docker compose up -d dev-database -d
    # How to remove container + volumes
    # -> docker compose rm dev-database --stop --force --volumes
